StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{64F04C0B992245AB}" {
   Id "SPC_EditableEntity_JLTV_CROWS_M240_Name"
   Target_en_us "M1278 - M240"
   Modified 1693471817
   Author "mikia"
   LastChanged "mikia"
  }
  CustomStringTableItem "{64F04C0B9BB99467}" {
   Id "SPC_EditableEntity_JLTV_CROWS_MK19_Name"
   Target_en_us "M1278 - MK19"
   Modified 1693471829
   Author "mikia"
   LastChanged "mikia"
  }
  CustomStringTableItem "{62A0219BFEEE91F1}" {
   Id "SPC_EditableEntity_JLTV_CROWS_Name"
   Target_en_us "M1278 - M2HB"
   Comment "Enity placed via the content Browser"
   ActorGender 2147483647
   Terminology 2147483647
   MaxLength 28
   Modified 1693402420
   Author "Ethan Benzel"
   LastChanged "mikia"
   Labels {
    300
   }
   SourceFile "{A19889DD96914B75}Prefabs/Vehicles/Wheeled/JLTV/CROWS_1/M2HB/JLTV_CROWS.et"
   ImageLink "https://bohemiainteractive.sharepoint.com/:i:/r/sites/reforger/translations/Images/JLTV_CROWS.png"
  }
  CustomStringTableItem "{644B4549E8A8821C}" {
   Id "SPC_EditableEntity_JLTV_CROWSII_Jav_Name"
   Target_en_us "M1278 - M230LF FGM147"
   Comment "Enity placed via the content Browser"
   ActorGender 2147483647
   Terminology 2147483647
   MaxLength 28
   Modified 1693402396
   Author "thoma"
   LastChanged "mikia"
   Labels {
    300
   }
   SourceFile "{9B906EE7402FDA06}Prefabs/Vehicles/Wheeled/JLTV/CROWS_2/Javelin/JLTV_CROWSII_Javelin.et"
   ImageLink "https://bohemiainteractive.sharepoint.com/:i:/r/sites/reforger/translations/Images/JLTV_CROWSII_Javelin.png"
  }
  CustomStringTableItem "{5C8898DF0DE55E65}" {
   Id "SPC_EditableEntity_JLTV_CROWSII_Name"
   Target_en_us "M1278 - M230LF"
   Comment "Enity placed via the content Browser"
   MaxLength 28
   Modified 1693402402
   Author "Ethan Benzel"
   LastChanged "mikia"
   Labels {
    300
   }
   SourceFile "{49B5C8D1F28E7B7F}Prefabs/Vehicles/Wheeled/JLTV/CROWS_2/JLTV_CROWSII.et"
  }
  CustomStringTableItem "{644B454839AEE092}" {
   Id "SPC_EditableEntity_JLTV_MADIS_MK1_Name"
   Target_en_us "AN/MSY-2(v)1"
   Comment "Enity placed via the content Browser"
   ActorGender 2147483647
   Terminology 2147483647
   MaxLength 28
   Modified 1693402053
   Author "mikia"
   LastChanged "mikia"
   Labels {
    300
   }
   SourceFile "{6BBA4A0E747D2215}Prefabs/Vehicles/Wheeled/JLTV/CROWS_2/AIM92/JLTV_CROWSII_AIM92.et"
   ImageLink "https://bohemiainteractive.sharepoint.com/:i:/r/sites/reforger/translations/Images/JLTV_CROWSII_AIM92.png"
  }
  CustomStringTableItem "{64EA53E3E6D53B43}" {
   Id "SPC_EditableEntity_JLTV_MADIS_MK2_Name"
   Target_en_us "AN/MSY-2(v)2"
   Modified 1693402056
   Author "mikia"
   LastChanged "mikia"
  }
  CustomStringTableItem "{64D573ED0F0C3BC4}" {
   Id "SPC_EditableEntity_JLTV_OGPK_M134_Name"
   Target_en_us "M1281 - M134"
   Modified 1693402465
   Author "mikia"
   LastChanged "mikia"
  }
  CustomStringTableItem "{64F04C0B8F9A7523}" {
   Id "SPC_EditableEntity_JLTV_OGPK_M240_Name"
   Target_en_us "M1281 - M240"
   Modified 1693471872
   Author "mikia"
   LastChanged "mikia"
  }
  CustomStringTableItem "{64F04C0B83ACAC8B}" {
   Id "SPC_EditableEntity_JLTV_OGPK_MK19_Name"
   Target_en_us "M1281 - MK19"
   Modified 1693471878
   Author "mikia"
   LastChanged "mikia"
  }
  CustomStringTableItem "{5C8898DF0DFD31FF}" {
   Id "SPC_EditableEntity_JLTV_OGPK_Name"
   Target_en_us "M1281 - M2HB"
   Comment "Enity placed via the content Browser"
   MaxLength 28
   Modified 1693402469
   Author "Ethan Benzel"
   LastChanged "mikia"
   Labels {
    300
   }
   SourceFile "{E49B4C9AEA70BE3F}Prefabs/Vehicles/Wheeled/JLTV/OGPK/M2HB/JLTV_OGPK.et"
  }
  CustomStringTableItem "{5C8898DF0DFFF41F}" {
   Id "SPC_EditableEntity_JLTV_Unarmed_Name"
   Target_en_us "M1280"
   Comment "Enity placed via the content Browser"
   MaxLength 28
   Modified 1693402474
   Author "Ethan Benzel"
   LastChanged "mikia"
   Labels {
    300
   }
   SourceFile "{E62EEF185EC31C54}Prefabs/Vehicles/Wheeled/JLTV/Unarmed/JLTV_Unarmed.et"
  }
 }
}